### ISSUE TITLE
File Manager issue copying small files version 4.88

### ISSUE THREAD

**Issue by whitezombie2000** [aldostools/IRISMAN#40] opened 2021-11-30 20:16 UTC
I tried to copy a small 24 byte PS2 config file (Xeno1iso.CONFIG) from USB0 to the internal HDD0 in my PS2ISO folder and it fails to copy. It looks like it performs the copy but nothing shows up in the folder. I can perform the move function from USB0 to HDD0 PS2ISO folder and it moves just fine. I can also successfully perform a copy from HDD0 PS2ISO to USB0 with no issue. 

I don't appear to have the problem with larger files. It seems to happen with small files. I was using Rebug firmware where the issue was present and updated to Evilnat 4.88.2 and the issue is still present so I don't think the firmware version matters. I don't appear to have issue with ManaGunZ or multiMAN.

**Comment by whitezombie2000** [comment] 2021-11-30 20:40
[Xeno1.iso.zip](https://github.com/aldostools/IRISMAN/files/7628738/Xeno1.iso.zip)

**Comment by aldostools** [comment] 2021-11-30 20:57
Thank you for your feedback. I just tested copying a rap file (16 bytes) from /dev_usb000 (FAT32) to /dev_hdd0/PS2ISO and the file was copied fine.


You don't mention if you're copying from FAT32, NTFS or exFAT. So I assume it was FAT32.
Also if you're using the File Manager or the exFAT File Manager extension (embedded Simple File Manager).

I suggest that try copying from a different USB device to verify if the issue is a corrupted file in the USB.

**Comment by whitezombie2000** [comment] 2021-11-30 21:07
Can you try copying the CONFIG file I attached? I can seem to copy other small files just fine but not the CONFIG file. Yes I tried another USB device and it behaves the same way and they are both FAT32. I'm not using any extension. The file is not corrupted because it is working like its supposed to when launching the game.

**Comment by whitezombie2000** [comment] 2021-11-30 21:24
In this video I try to copy it to the PS3ISO folder because I already have it in the PS2ISO folder.

**Comment by aldostools** [comment] 2021-11-30 21:34
Thank you for the information. I managed to reproduce the bug.
The issue is due the extension .iso.* that is being confused as a split ISO. 

I will check it in detail and post a fix so you can test it.

**Comment by whitezombie2000** [comment] 2021-11-30 21:38
Ahhhh!! Yes!! If you take ISO out of the name it copies just fine. Good find!

**Comment by aldostools** [comment] 2021-12-01 00:33
The issue has been fixed in the latest commit.
You can download the latest installer from breowlogy or from the release page
https://github.com/aldostools/IRISMAN/releases

**Closed as completed by aldostools** 2021-12-01 00:33 UTC
